# Generated by Django 3.1.13 on 2022-02-21 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officers', '0025_rename_event_complaint_uid_to_allegation_uid'),
        ('departments', '0015_add_department_starred_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appeal_uid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('docket_no', models.CharField(blank=True, max_length=255, null=True)),
                ('counsel', models.CharField(blank=True, max_length=255, null=True)),
                ('charging_supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('appeal_disposition', models.CharField(blank=True, max_length=255, null=True)),
                ('action_appealed', models.CharField(blank=True, max_length=255, null=True)),
                ('appealed', models.CharField(blank=True, max_length=255, null=True)),
                ('motions', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='departments.department')),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='officers.officer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
