# Generated by Django 3.1.13 on 2023-02-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_create_appeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='appealed',
        ),
    ]
