# Generated by Django 3.1.13 on 2023-02-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_add_uid_and_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='counsel',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='docket_no',
        ),
    ]
