from django.db import models

from utils.models import TimeStampsModel


class UseOfForce(TimeStampsModel):
    uof_uid = models.CharField(max_length=255, unique=True, db_index=True)
    uof_tracking_number = models.CharField(max_length=255, null=True, blank=True)
    report_year = models.IntegerField(null=True, blank=True)
    force_description = models.CharField(max_length=255, null=True, blank=True)
    force_type = models.CharField(max_length=255, null=True, blank=True)
    force_level = models.CharField(max_length=255, null=True, blank=True)
    effective_uof = models.CharField(max_length=255, null=True, blank=True)
    accidental_discharge = models.CharField(max_length=255, null=True, blank=True)
    less_than_lethal = models.CharField(max_length=255, null=True, blank=True)
    status = models.CharField(max_length=255, null=True, blank=True)
    source = models.CharField(max_length=255, null=True, blank=True)
    service_type = models.CharField(max_length=255, null=True, blank=True)
    county = models.CharField(max_length=255, null=True, blank=True)
    traffic_stop = models.CharField(max_length=255, null=True, blank=True)
    sustained = models.CharField(max_length=255, null=True, blank=True)
    force_reason = models.CharField(max_length=255, null=True, blank=True)
    weather_description = models.CharField(max_length=255, null=True, blank=True)
    distance_from_officer = models.CharField(max_length=255, null=True, blank=True)
    body_worn_camera_available = models.CharField(max_length=255, null=True, blank=True)
    app_used = models.CharField(max_length=255, null=True, blank=True)
    citizen_arrested = models.CharField(max_length=255, null=True, blank=True)
    citizen_hospitalized = models.CharField(max_length=255, null=True, blank=True)
    citizen_injured = models.CharField(max_length=255, null=True, blank=True)
    citizen_body_type = models.CharField(max_length=255, null=True, blank=True)
    citizen_height = models.CharField(max_length=255, null=True, blank=True)
    citizen_age = models.IntegerField(null=True, blank=True)
    citizen_involvement = models.CharField(max_length=255, null=True, blank=True)
    disposition = models.CharField(max_length=255, null=True, blank=True)
    citizen_sex = models.CharField(max_length=255, null=True, blank=True)
    citizen_race = models.CharField(max_length=255, null=True, blank=True)
    citizen_age_1 = models.CharField(max_length=255, null=True, blank=True)
    officer_current_supervisor = models.CharField(max_length=255, null=True, blank=True)
    officer_title = models.CharField(max_length=255, null=True, blank=True)
    officer_injured = models.CharField(max_length=255, null=True, blank=True)
    officer_age = models.CharField(max_length=255, null=True, blank=True)
    officer_years_exp = models.IntegerField(null=True, blank=True)
    officer_years_with_unit = models.IntegerField(null=True, blank=True)
    officer_type = models.CharField(max_length=255, null=True, blank=True)
    officer_employment_status = models.CharField(max_length=255, null=True, blank=True)
    officer_department = models.CharField(max_length=255, null=True, blank=True)
    officer_division = models.CharField(max_length=255, null=True, blank=True)
    officer_sub_division_a = models.CharField(max_length=255, null=True, blank=True)
    officer_sub_division_b = models.CharField(max_length=255, null=True, blank=True)
    data_production_year = models.IntegerField(null=True, blank=True)

    officer = models.ForeignKey('officers.Officer', on_delete=models.CASCADE, null=True, related_name='use_of_forces')
    department = models.ForeignKey(
        'departments.Department', on_delete=models.CASCADE, null=True, related_name='use_of_forces'
    )
