# Generated by Django 3.1.4 on 2021-01-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0001_create_app_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTextContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('value', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
