# Generated by Django 3.1.4 on 2021-05-11 09:35

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0002_create_app_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptextcontent',
            name='value',
            field=martor.models.MartorField(),
        ),
    ]
