# Generated by Django 3.1.4 on 2021-09-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0003_change_value_field_as_md_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
