# Generated by Django 3.1.13 on 2022-05-17 08:25

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0004_create_model_front_page_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('content', martor.models.MartorField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
