# Generated by Django 3.1.13 on 2022-09-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0005_create_frontpage_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppConfig',
            new_name='AppValueConfig',
        ),
    ]
