# Generated by Django 3.1.13 on 2022-09-26 07:27

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0006_rename_model_to_app_value_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptextcontent',
            name='value',
            field=martor.models.MartorField(blank=True, null=True),
        ),
    ]
