OFFICERS_LIMIT = 20

JOINED_TIMELINE_KIND = 'JOINED'
LEFT_TIMELINE_KIND = 'LEFT'
COMPLAINT_TIMELINE_KIND = 'COMPLAINT'
DOCUMENT_TIMELINE_KIND = 'DOCUMENT'
SALARY_CHANGE_TIMELINE_KIND = 'SALARY_CHANGE'
