OFFICERS_LIMIT = 20

JOINED_TIMELINE_KIND = 'JOINED'
LEFT_TIMELINE_KIND = 'LEFT'
COMPLAINT_TIMELINE_KIND = 'COMPLAINT'
UOF_TIMELINE_KIND = 'UOF'
DOCUMENT_TIMELINE_KIND = 'DOCUMENT'
SALARY_CHANGE_TIMELINE_KIND = 'SALARY_CHANGE'
RANK_CHANGE_TIMELINE_KIND = 'RANK_CHANGE'
UNIT_CHANGE_TIMELINE_KIND = 'UNIT_CHANGE'

OFFICER_LEVEL_1_CERT = "officer_level_1_cert"
OFFICER_PC_12_QUALIFICATION = "officer_pc_12_qualification"
OFFICER_RANK = "officer_rank"
OFFICER_DEPT = "officer_dept"
OFFICER_HIRE = "officer_hire"
OFFICER_LEFT = "officer_left"
OFFICER_PAY_PROG_START = "officer_pay_prog_start"
OFFICER_PAY_EFFECTIVE = "officer_pay_effective"

COMPLAINT_INCIDENT = "complaint_incident"
COMPLAINT_RECEIVE = "complaint_receive"
ALLEGATION_CREATE = "allegation_create"
INVESTIGATION_COMPLETE = "investigation_complete"
SUSPENSION_START = "suspension_start"
SUSPENSION_END = "suspension_end"

APPEAL_FILE = "appeal_file"
APPEAL_HEARING = "appeal_hearing"
APPEAL_RENDER = "appeal_render"

UOF_INCIDENT = "uof_incident"
UOF_RECEIVE = "uof_receive"
UOF_ASSIGNED = "uof_assigned"
UOF_COMPLETED = "uof_completed"
UOF_CREATED = "uof_created"
UOF_DUE = "uof_due"

AWARD_RECEIVE = "award_receive"

COMPLAINT_EVENT_KINDS = [
    COMPLAINT_INCIDENT,
    COMPLAINT_RECEIVE,
    ALLEGATION_CREATE,
    INVESTIGATION_COMPLETE,
    SUSPENSION_START,
    SUSPENSION_END,
]

EVENT_KINDS = (
    (OFFICER_LEVEL_1_CERT, OFFICER_LEVEL_1_CERT),
    (OFFICER_PC_12_QUALIFICATION, OFFICER_PC_12_QUALIFICATION),
    (OFFICER_RANK, OFFICER_RANK),
    (OFFICER_DEPT, OFFICER_DEPT),
    (OFFICER_HIRE, OFFICER_HIRE),
    (OFFICER_LEFT, OFFICER_LEFT),
    (OFFICER_PAY_PROG_START, OFFICER_PAY_PROG_START),
    (OFFICER_PAY_EFFECTIVE, OFFICER_PAY_EFFECTIVE),
    (COMPLAINT_INCIDENT, COMPLAINT_INCIDENT),
    (COMPLAINT_RECEIVE, COMPLAINT_RECEIVE),
    (ALLEGATION_CREATE, ALLEGATION_CREATE),
    (INVESTIGATION_COMPLETE, INVESTIGATION_COMPLETE),
    (SUSPENSION_START, SUSPENSION_START),
    (SUSPENSION_END, SUSPENSION_END),
    (APPEAL_FILE, APPEAL_FILE),
    (APPEAL_HEARING, APPEAL_HEARING),
    (APPEAL_RENDER, APPEAL_RENDER),
    (UOF_INCIDENT, UOF_INCIDENT),
    (UOF_RECEIVE, UOF_RECEIVE),
    (UOF_ASSIGNED, UOF_ASSIGNED),
    (UOF_COMPLETED, UOF_COMPLETED),
    (UOF_CREATED, UOF_CREATED),
    (UOF_DUE, UOF_DUE),
    (AWARD_RECEIVE, AWARD_RECEIVE),
)
