# Generated by Django 3.1.4 on 2021-02-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officers', '0002_allow_blank_officer_history_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('incident_date', models.DateField(null=True)),
                ('officers', models.ManyToManyField(blank=True, to='officers.Officer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
