# Generated by Django 3.1.4 on 2021-02-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_wrglfile'),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='uid',
        ),
        migrations.AddField(
            model_name='complaint',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant_sex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='data_production_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='departments',
            field=models.ManyToManyField(blank=True, to='departments.Department'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='disposition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='investigation_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='occur_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='occur_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='occur_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='occur_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='paragraph_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='paragraph_violation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='receive_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='receive_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='receive_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rule_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rule_violation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='supervisor_rank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='supervisor_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='suspension_end_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='suspension_end_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='suspension_end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='suspension_start_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='suspension_start_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='suspension_start_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
