# Generated by Django 3.1.4 on 2021-03-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_add_fields_to_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='occur_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='occur_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='occur_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='receive_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='receive_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='receive_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='suspension_end_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='suspension_end_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='suspension_end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='suspension_start_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='suspension_start_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='suspension_start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
