# Generated by Django 3.1.4 on 2021-04-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0012_event'),
        ('complaints', '0004_add_more_fields_to_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='events',
            field=models.ManyToManyField(blank=True, to='officers.Event'),
        ),
    ]
