# Generated by Django 3.1.4 on 2021-04-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='charges',
            field=models.TextField(blank=True, null=True),
        ),
    ]
