# Generated by Django 3.1.4 on 2021-05-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_add_related_name_for_complaint_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complainant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='employment_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
