# Generated by Django 3.1.13 on 2021-12-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_add_fields_to_complaint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together={('complaint_uid',)},
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='allegation_uid',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='charge_uid',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='data_production_year',
        ),
    ]
