# Generated by Django 3.1.13 on 2021-12-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_remove_wrgl_deleted_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_uid',
            new_name='allegation_uid',
        ),
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together={('allegation_uid',)},
        ),
    ]
