# Generated by Django 3.1.13 on 2021-12-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_add_traffic_stop_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='allegation_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
