# Generated by Django 3.1.13 on 2022-03-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_add_allegation_desc_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='allegation_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
