# Generated by Django 3.1.13 on 2022-06-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0014_change_allegation_desc_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='allegation_class',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='allegation_finding',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_sub_division_a',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_unit',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='investigation_type',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='paragraph_code',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='paragraph_violation',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='rank_desc',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='recommended_action',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='rule_code',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='rule_violation',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='complaint',
            name='case_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='disposition_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='incident_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='initial_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='investigating_department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='investigator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='investigator_rank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='investigator_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='referred_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='shift_supervisor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='allegation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
