# Generated by Django 3.1.13 on 2023-04-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_remove_dispensable_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='coaccusal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
