# Generated by Django 3.1.4 on 2021-02-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerhistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officerhistory',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
