# Generated by Django 3.1.4 on 2021-02-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0003_allow_null_for_officer_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='uid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
