# Generated by Django 3.1.4 on 2021-02-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0004_add_unique_for_officer_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerhistory',
            name='agency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='data_production_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='department_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='department_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='hire_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='hire_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='hire_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='hourly_salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='pay_effective_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='pay_effective_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='pay_effective_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='rank_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='term_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='term_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='term_year',
            field=models.IntegerField(null=True),
        ),
    ]
