# Generated by Django 3.1.4 on 2021-03-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0007_allow_blank_for_officer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerhistory',
            name='annual_salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
