# Generated by Django 3.1.4 on 2021-03-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0008_officerhistory_annual_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='race',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
