# Generated by Django 3.1.4 on 2021-04-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0009_add_race_and_gender_to_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerhistory',
            name='rank_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='rank_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officerhistory',
            name='rank_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
