# Generated by Django 3.1.4 on 2021-04-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_remove_department_officers'),
        ('officers', '0010_add_rank_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='departments',
        ),
        migrations.DeleteModel(
            name='OfficerHistory',
        ),
    ]
