# Generated by Django 3.1.4 on 2021-04-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_remove_department_officers'),
        ('officers', '0011_remove_officerhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('officer_level_1_cert', 'officer_level_1_cert'), ('officer_pc_12_qualification', 'officer_pc_12_qualification'), ('officer_rank', 'officer_rank'), ('officer_dept', 'officer_dept'), ('officer_hire', 'officer_hire'), ('officer_left', 'officer_left'), ('officer_pay_prog_start', 'officer_pay_prog_start'), ('officer_pay_effective', 'officer_pay_effective'), ('complaint_incident', 'complaint_incident'), ('complaint_receive', 'complaint_receive'), ('allegation_create', 'allegation_create'), ('investigation_complete', 'investigation_complete'), ('suspension_start', 'suspension_start'), ('suspension_end', 'suspension_end'), ('appeal_file', 'appeal_file'), ('appeal_hearing', 'appeal_hearing'), ('appeal_render', 'appeal_render'), ('uof_incident', 'uof_incident'), ('uof_receive', 'uof_receive'), ('uof_assigned', 'uof_assigned'), ('uof_completed', 'uof_completed'), ('uof_created', 'uof_created'), ('uof_due', 'uof_due')], max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_date', models.CharField(blank=True, max_length=255, null=True)),
                ('badge_no', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('department_code', models.CharField(blank=True, max_length=255, null=True)),
                ('department_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('division_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_division_a_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_division_b_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('current_supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_code', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=255, null=True)),
                ('officer_inactive', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_type', models.CharField(blank=True, max_length=255, null=True)),
                ('years_employed', models.IntegerField(blank=True, null=True)),
                ('annual_salary', models.CharField(blank=True, max_length=255, null=True)),
                ('hourly_salary', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officers.officer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
