# Generated by Django 3.1.4 on 2021-04-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0013_update_officer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[
                ('officer_level_1_cert', 'officer_level_1_cert'),
                ('officer_pc_12_qualification', 'officer_pc_12_qualification'),
                ('officer_rank', 'officer_rank'),
                ('officer_dept', 'officer_dept'),
                ('officer_hire', 'officer_hire'),
                ('officer_left', 'officer_left'),
                ('officer_pay_prog_start', 'officer_pay_prog_start'),
                ('officer_pay_effective', 'officer_pay_effective'),
                ('complaint_incident', 'complaint_incident'),
                ('complaint_receive', 'complaint_receive'),
                ('allegation_create', 'allegation_create'),
                ('investigation_complete', 'investigation_complete'),
                ('suspension_start', 'suspension_start'),
                ('suspension_end', 'suspension_end'),
                ('appeal_file', 'appeal_file'),
                ('appeal_hearing', 'appeal_hearing'),
                ('appeal_render', 'appeal_render'),
                ('uof_incident', 'uof_incident'),
                ('uof_receive', 'uof_receive'),
                ('uof_assigned', 'uof_assigned'),
                ('uof_completed', 'uof_completed'),
                ('uof_created', 'uof_created'),
                ('uof_due', 'uof_due'),
                ('award_receive', 'award_receive')
            ], db_index=True, max_length=255),
        ),
    ]
