# Generated by Django 3.1.4 on 2021-05-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('use_of_forces', '0001_create_use_of_force'),
        ('officers', '0015_remove_event_use_of_force_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='use_of_force',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='use_of_forces.useofforce'),
        ),
    ]
