# Generated by Django 3.1.4 on 2021-05-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0016_event_use_of_force'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='annual_salary',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hourly_salary',
        ),
        migrations.AddField(
            model_name='event',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='salary_freq',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
