# Generated by Django 3.1.4 on 2021-05-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0017_change_event_salary_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_uid',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
