# Generated by Django 3.1.4 on 2021-05-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_department_officers'),
        ('officers', '0018_add_unique_constraint_to_event_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='event',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='officers.officer'),
        ),
    ]
