# Generated by Django 3.1.4 on 2021-05-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0019_add_related_name_for_event_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='officer_inactive',
        ),
        migrations.AddField(
            model_name='event',
            name='award',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='award_comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='employee_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_inactive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sworn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
