# Generated by Django 3.1.4 on 2021-05-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0020_add_fields_to_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='allegation_uid',
        ),
    ]
