# Generated by Django 3.1.4 on 2021-11-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0023_add_officer_relation_to_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='is_name_changed',
            field=models.BooleanField(default=False),
        ),
    ]
