# Generated by Django 3.1.13 on 2021-12-07 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0024_add_field_is_name_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='complaint_uid',
            new_name='allegation_uid',
        ),
    ]
