# Generated by Django 3.1.13 on 2022-03-03 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_create_appeal'),
        ('officers', '0025_rename_event_complaint_uid_to_allegation_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='appeal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='appeals.appeal'),
        ),
    ]
