# Generated by Django 3.1.13 on 2022-06-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0027_update_kind_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_inactive',
            new_name='officer_inactive',
        ),
        migrations.RemoveField(
            model_name='event',
            name='employment_status',
        ),
        migrations.AddField(
            model_name='event',
            name='left_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
