# Generated by Django 3.1.13 on 2022-06-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0028_remove_employment_status_add_left_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='middle_initial',
        ),
        migrations.AddField(
            model_name='officer',
            name='sex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
