# Generated by Django 3.1.13 on 2022-06-16 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0019_remove_department_officers'),
        ('officers', '0029_rename_gender_to_sex_remove_middle_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='departments',
        ),
        migrations.AddField(
            model_name='officer',
            name='agency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='departments.department'),
        ),
    ]
