# Generated by Django 3.1.13 on 2022-09-15 08:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0030_change_department_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
