# Generated by Django 3.1.13 on 2022-10-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0031_add_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='complaint_fraction',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
