# Generated by Django 3.1.13 on 2023-01-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0032_add_complaint_fraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(blank=True, choices=[('officer_level_1_cert', 'Officer Level 1 Cert'), ('officer_pc_12_qualification', 'Officer Pc 12 Qualification'), ('officer_rank', 'Officer Rank'), ('officer_dept', 'Officer Dept'), ('officer_hire', 'Officer Hire'), ('officer_left', 'Officer Left'), ('officer_pay_prog_start', 'Officer Pay Prog Start'), ('officer_pay_effective', 'Officer Pay Effective'), ('complaint_incident', 'Complaint Incident'), ('complaint_receive', 'Complaint Receive'), ('allegation_create', 'Allegation Create'), ('investigation_complete', 'Investigation Complete'), ('suspension_start', 'Suspension Start'), ('suspension_end', 'Suspension End'), ('appeal_file', 'Appeal File'), ('appeal_hearing', 'Appeal Hearing'), ('appeal_render', 'Appeal Render'), ('uof_incident', 'Uof Incident'), ('uof_receive', 'Uof Receive'), ('uof_assigned', 'Uof Assigned'), ('uof_completed', 'Uof Completed'), ('uof_created', 'Uof Created'), ('uof_due', 'Uof Due'), ('award_receive', 'Award Receive')], db_index=True, max_length=255, null=True),
        ),
    ]
