# Generated by Django 3.1.13 on 2023-02-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0033_make_kind_field_have_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='award',
        ),
        migrations.RemoveField(
            model_name='event',
            name='award_comments',
        ),
        migrations.RemoveField(
            model_name='event',
            name='current_supervisor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='division_desc',
        ),
        migrations.RemoveField(
            model_name='event',
            name='employee_class',
        ),
        migrations.RemoveField(
            model_name='event',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='employee_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='officer_inactive',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sub_division_a_desc',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sub_division_b_desc',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sworn',
        ),
        migrations.RemoveField(
            model_name='event',
            name='years_employed',
        ),
    ]
