# Generated by Django 3.1.13 on 2023-02-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0034_remove_dispensable_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='agency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='uof_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
