# Generated by Django 3.1.13 on 2023-02-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0035_add_agency_uid_uof_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='division_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='overtime_annual_total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
