# Generated by Django 3.1.13 on 2023-02-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0036_add_optional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='overtime_annual_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
