# Generated by Django 3.1.13 on 2023-04-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0037_change_overtime_annual_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='award',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
