# Generated by Django 3.1.13 on 2023-04-13 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brady', '0001_create_brady'),
        ('officers', '0038_add_award_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='brady',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='brady.brady'),
        ),
        migrations.AddField(
            model_name='event',
            name='brady_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(blank=True, choices=[('officer_level_1_cert', 'Officer Level 1 Cert'), ('officer_pc_12_qualification', 'Officer Pc 12 Qualification'), ('officer_rank', 'Officer Rank'), ('officer_dept', 'Officer Dept'), ('officer_hire', 'Officer Hire'), ('officer_left', 'Officer Left'), ('officer_pay_prog_start', 'Officer Pay Prog Start'), ('officer_pay_effective', 'Officer Pay Effective'), ('complaint_incident', 'Complaint Incident'), ('complaint_receive', 'Complaint Receive'), ('allegation_create', 'Allegation Create'), ('investigation_complete', 'Investigation Complete'), ('suspension_start', 'Suspension Start'), ('suspension_end', 'Suspension End'), ('appeal_file', 'Appeal File'), ('appeal_hearing', 'Appeal Hearing'), ('appeal_render', 'Appeal Render'), ('uof_incident', 'Uof Incident'), ('uof_receive', 'Uof Receive'), ('uof_assigned', 'Uof Assigned'), ('uof_completed', 'Uof Completed'), ('uof_created', 'Uof Created'), ('uof_due', 'Uof Due'), ('award_receive', 'Award Receive'), ('brady_list', 'Brady List')], db_index=True, max_length=255, null=True),
        ),
    ]
