# Generated by Django 3.1.13 on 2022-09-28 03:49

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0001_create_section_and_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=martor.models.MartorField(blank=True, null=True),
        ),
    ]
