# Generated by Django 3.1.4 on 2021-05-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officers', '0015_remove_event_use_of_force_uid'),
        ('departments', '0006_department_officers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseOfForce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uof_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('uof_tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('report_year', models.IntegerField(blank=True, null=True)),
                ('force_description', models.CharField(blank=True, max_length=255, null=True)),
                ('force_type', models.CharField(blank=True, max_length=255, null=True)),
                ('force_level', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_uof', models.CharField(blank=True, max_length=255, null=True)),
                ('accidental_discharge', models.CharField(blank=True, max_length=255, null=True)),
                ('less_than_lethal', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('service_type', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('traffic_stop', models.CharField(blank=True, max_length=255, null=True)),
                ('sustained', models.CharField(blank=True, max_length=255, null=True)),
                ('force_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('weather_description', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_from_officer', models.CharField(blank=True, max_length=255, null=True)),
                ('body_worn_camera_available', models.CharField(blank=True, max_length=255, null=True)),
                ('app_used', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_arrested', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_hospitalized', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_injured', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_body_type', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_height', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_age', models.IntegerField(blank=True, null=True)),
                ('citizen_involvement', models.CharField(blank=True, max_length=255, null=True)),
                ('disposition', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_sex', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_race', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_age_1', models.CharField(blank=True, max_length=255, null=True)),
                ('officer_current_supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('officer_title', models.CharField(blank=True, max_length=255, null=True)),
                ('officer_injured', models.CharField(blank=True, max_length=255, null=True)),
                ('officer_age', models.CharField(blank=True, max_length=255, null=True)),
                ('officer_years_exp', models.IntegerField(blank=True, null=True)),
                ('officer_years_with_unit', models.IntegerField(blank=True, null=True)),
                ('officer_type', models.CharField(blank=True, max_length=255, null=True)),
                ('officer_employment_status', models.CharField(blank=True, max_length=255, null=True)),
                ('officer_department', models.CharField(blank=True, max_length=255, null=True)),
                ('officer_division', models.CharField(blank=True, max_length=255, null=True)),
                ('officer_sub_division_a', models.CharField(blank=True, max_length=255, null=True)),
                ('officer_sub_division_b', models.CharField(blank=True, max_length=255, null=True)),
                ('data_production_year', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_of_forces', to='officers.officer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
