# Generated by Django 3.1.4 on 2021-05-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_department_officers'),
        ('use_of_forces', '0002_add_db_index_for_use_of_force_uof_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useofforce',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_of_forces', to='departments.department'),
        ),
    ]
