# Generated by Django 3.1.4 on 2021-05-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_of_forces', '0003_add_related_name_for_use_of_force_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='useofforce',
            name='citizen_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
