# Generated by Django 3.1.13 on 2022-05-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0026_add_appeal_relation_to_events'),
        ('use_of_forces', '0004_useofforce_citizen_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useofforce',
            name='accidental_discharge',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='app_used',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='body_worn_camera_available',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='citizen_age',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='citizen_age_1',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='citizen_arrested',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='citizen_body_type',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='citizen_height',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='citizen_hospitalized',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='citizen_injured',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='citizen_involvement',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='citizen_race',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='citizen_sex',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='citizen_uid',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='county',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='data_production_year',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='distance_from_officer',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='effective_uof',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='force_description',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='force_level',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='force_reason',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='force_type',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='less_than_lethal',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='officer_age',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='officer_current_supervisor',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='officer_department',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='officer_division',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='officer_employment_status',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='officer_injured',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='officer_sub_division_a',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='officer_sub_division_b',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='officer_title',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='officer_type',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='officer_years_exp',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='officer_years_with_unit',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='report_year',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='source',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='status',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='sustained',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='traffic_stop',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='uof_tracking_number',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='weather_description',
        ),
        migrations.AddField(
            model_name='useofforce',
            name='agency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useofforce',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useofforce',
            name='division_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useofforce',
            name='investigation_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useofforce',
            name='light_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useofforce',
            name='originating_bureau',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useofforce',
            name='shift_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useofforce',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useofforce',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useofforce',
            name='use_of_force_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useofforce',
            name='weather_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UseOfForceOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uof_uid', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('use_of_force_description', models.CharField(blank=True, max_length=255, null=True)),
                ('use_of_force_level', models.CharField(blank=True, max_length=255, null=True)),
                ('use_of_force_effective', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('years_of_service', models.IntegerField(blank=True, null=True)),
                ('officer_injured', models.CharField(blank=True, max_length=255, null=True)),
                ('officer', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='uof_officers',
                    to='officers.officer'
                )),
                ('use_of_force', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='uof_officers',
                    to='use_of_forces.useofforce'
                )),
            ],
            options={
                'unique_together': {('uof_uid', 'uid')},
            },
        ),
        migrations.CreateModel(
            name='UseOfForceCitizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uof_citizen_uid', models.CharField(max_length=255)),
                ('uof_uid', models.CharField(max_length=255)),
                ('citizen_influencing_factors', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_distance_from_officer', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_arrested', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_arrest_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_hospitalized', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_injured', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_age', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_race', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_sex', models.CharField(blank=True, max_length=255, null=True)),
                ('use_of_force', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='uof_citizens',
                    to='use_of_forces.useofforce'
                )),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='useofforce',
            name='officers',
            field=models.ManyToManyField(related_name='use_of_forces', through='use_of_forces.UseOfForceOfficer', to='officers.Officer'),
        ),
    ]
