# Generated by Django 3.1.13 on 2022-05-10 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0026_add_appeal_relation_to_events'),
        ('use_of_forces', '0005_update_use_of_force_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseOfForceOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uof_uid', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('use_of_force_type', models.CharField(blank=True, max_length=255, null=True)),
                ('use_of_force_level', models.CharField(blank=True, max_length=255, null=True)),
                ('use_of_force_effective', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('years_of_service', models.IntegerField(blank=True, null=True)),
                ('officer_injured', models.CharField(blank=True, max_length=255, null=True)),
                ('officer', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='uof_officers',
                    to='officers.officer'
                )),
                ('use_of_force', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='uof_officers',
                    to='use_of_forces.useofforce'
                )),
            ],
            options={
                'unique_together': {('uof_uid', 'uid')},
            },
        ),
        migrations.AddField(
            model_name='useofforce',
            name='officers',
            field=models.ManyToManyField(related_name='use_of_forces', through='use_of_forces.UseOfForceOfficer', to='officers.Officer'),
        ),
    ]
