# Generated by Django 3.1.13 on 2023-02-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use_of_forces', '0005_update_uof_create_uof_officer_and_uof_citizen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useofforce',
            name='division',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='division_level',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='investigation_status',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='light_condition',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='originating_bureau',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='shift_time',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='weather_condition',
        ),
    ]
