# Generated by Django 3.1.13 on 2023-02-13 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0035_add_agency_uid_uof_uid'),
        ('use_of_forces', '0006_remove_dispensable_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='useofforce',
            name='officer_injured',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useofforce',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useofforce',
            name='use_of_force_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='useofforce',
            name='officers',
        ),
        migrations.AddField(
            model_name='useofforce',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_of_forces', to='officers.officer'),
        ),
    ]
