# Generated by Django 3.1.13 on 2022-05-12 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('use_of_forces', '0006_create_uof_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseOfForceCitizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uof_citizen_uid', models.CharField(max_length=255)),
                ('uof_uid', models.CharField(max_length=255)),
                ('citizen_influencing_factors', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_distance_from_officer', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_arrested', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_arrest_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_hospitalized', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_injured', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_build', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_height', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_sex', models.CharField(blank=True, max_length=255, null=True)),
                ('use_of_force', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='uof_citizens',
                    to='use_of_forces.useofforce'
                )),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
