# Generated by Django 3.1.13 on 2023-02-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use_of_forces', '0007_update_uof_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UseOfForceOfficer',
        ),
    ]
