# Generated by Django 3.1.13 on 2023-02-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use_of_forces', '0008_delete_useofforceofficer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UseOfForceCitizen',
        ),
    ]
