# Generated by Django 3.1.4 on 2021-05-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_model', models.CharField(max_length=255)),
                ('repo_name', models.CharField(max_length=255, null=True)),
                ('commit_hash', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('no_new_commit', 'No new commit'), ('running', 'Running'), ('finished', 'Finished'), ('error', 'Error')], max_length=32)),
                ('created_rows', models.IntegerField(null=True)),
                ('updated_rows', models.IntegerField(null=True)),
                ('deleted_rows', models.IntegerField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('error_message', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WrglRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_model', models.CharField(max_length=255, unique=True)),
                ('repo_name', models.CharField(max_length=255)),
                ('commit_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
