# Generated by Django 3.1.4 on 2021-05-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='error_message',
            field=models.TextField(null=True),
        ),
    ]
