# Generated by Django 3.1.13 on 2021-12-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_change_importlog_error_message_to_text_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='status',
            field=models.CharField(
                choices=[
                    ('started', 'Started'),
                    ('no_new_commit', 'No new commit'),
                    ('no_new_data', 'No new data'),
                    ('running', 'Running'),
                    ('finished', 'Finished'),
                    ('error', 'Error')
                ],
                max_length=32),
        ),
    ]
