# Generated by Django 3.1.13 on 2023-02-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_add_no_new_data_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrglrepo',
            name='latest_commit_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
