# Generated by Django 3.1.13 on 2024-04-08 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0004_add_latest_commit_hash"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WrglRepo",
        ),
    ]
