# Generated by Django 3.1.4 on 2021-01-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='officers',
            field=models.ManyToManyField(through='officers.OfficerHistory', to='officers.Officer'),
        ),
    ]
