# Generated by Django 3.1.4 on 2021-02-17 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_officers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrglFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('download_url', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0, unique=True)),
                ('default_expanded', models.BooleanField(default=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
