# Generated by Django 3.1.4 on 2021-04-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_unique_wrgl_position_by_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='officers',
        ),
    ]
