# Generated by Django 3.1.4 on 2021-04-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0012_event'),
        ('departments', '0005_remove_department_officers'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='officers',
            field=models.ManyToManyField(through='officers.Event', to='officers.Officer'),
        ),
    ]
