# Generated by Django 3.1.4 on 2021-05-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_department_officers'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
