# Generated by Django 3.1.4 on 2021-05-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0009_add_unique_and_index_for_department_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrglfile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrgl_files', to='departments.department'),
        ),
    ]
