# Generated by Django 3.1.13 on 2021-12-15 08:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0010_add_related_name_for_wrgl_file_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='data_period',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
