# Generated by Django 3.1.13 on 2021-12-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0011_add_department_data_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
