# Generated by Django 3.1.13 on 2021-12-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0025_rename_event_complaint_uid_to_allegation_uid'),
        ('departments', '0012_add_department_phone_and_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='starred_officers',
            field=models.ManyToManyField(blank=True, related_name='starred_departments', to='officers.Officer'),
        ),
    ]
