# Generated by Django 3.1.13 on 2022-03-16 08:53

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0015_add_department_starred_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={}, null=True),
        ),
    ]
