# Generated by Django 3.1.13 on 2022-03-22 03:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0016_add_location_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='data_period',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
