# Generated by Django 3.1.13 on 2022-05-16 09:34

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0017_allow_empty_data_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'readonly': False}, null=True),
        ),
    ]
