# Generated by Django 3.1.13 on 2022-06-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0018_make_location_field_editable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='officers',
        ),
    ]
