# Generated by Django 3.1.13 on 2022-09-15 07:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0019_remove_department_officers'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
