# Generated by Django 3.1.13 on 2022-10-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0020_add_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='officer_fraction',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
