# Generated by Django 3.1.13 on 2022-11-29 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('officers', '0032_add_complaint_fraction'),
        ('departments', '0021_add_officer_fraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('left_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('end_department',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_movements',
                                   to='departments.department')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements',
                                              to='officers.officer')),
                ('start_department',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_movements',
                                   to='departments.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
