# Generated by Django 3.1.13 on 2023-02-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0022_create_officer_movement_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='agency_name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='slug',
            new_name='agency_slug',
        ),
    ]
