# Generated by Django 3.1.4 on 2021-09-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial_tasks_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
