# Generated by Django 3.1.4 on 2021-08-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0002_create_model_news_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
