# Generated by Django 3.1.4 on 2021-08-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0003_newsarticle_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='preview_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
