# Generated by Django 3.1.4 on 2021-08-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0021_remove_event_allegation_uid'),
        ('news_articles', '0004_newsarticle_preview_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='officers',
            field=models.ManyToManyField(blank=True, related_name='news_articles', to='officers.Officer'),
        ),
    ]
