# Generated by Django 3.1.4 on 2021-08-31 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0005_newsarticle_officers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawledpost',
            old_name='name',
            new_name='source_name',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='name',
            new_name='source_name',
        ),
    ]
