# Generated by Django 3.1.4 on 2021-09-01 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0008_create_model_crawler_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_url', models.CharField(max_length=10000)),
                ('response_status_code', models.CharField(max_length=32)),
                ('error_message', models.TextField(null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='news_articles.crawlerlog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
