# Generated by Django 3.1.4 on 2021-09-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0009_create_model_crawler_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='preview_image_url',
        ),
    ]
