# Generated by Django 3.1.4 on 2021-09-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0010_remove_newsarticle_preview_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticleSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(max_length=255)),
                ('custom_matching_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
