# Generated by Django 3.1.4 on 2021-09-14 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0011_create_model_news_article_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawledpost',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='crawlerlog',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='source_name',
        ),
        migrations.AddField(
            model_name='crawledpost',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_articles.newsarticlesource'),
        ),
        migrations.AddField(
            model_name='crawlerlog',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_articles.newsarticlesource'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_articles.newsarticlesource'),
        ),
    ]
