# Generated by Django 3.1.4 on 2021-09-20 11:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0012_alter_source_name_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ran_at', models.DateTimeField(blank=True, null=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
