# Generated by Django 3.1.4 on 2021-09-20 11:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0013_create_model_matching_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='extracted_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
