# Generated by Django 3.1.4 on 2021-09-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0022_alter_event_department_uof_fields'),
        ('news_articles', '0014_newsarticle_extracted_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludeOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ran_at', models.DateTimeField(blank=True, null=True)),
                ('officers', models.ManyToManyField(blank=True, related_name='exclude_officers', to='officers.Officer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
