# Generated by Django 3.1.4 on 2021-09-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0022_alter_event_department_uof_fields'),
        ('news_articles', '0015_create_model_exclude_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='excluded_officers',
            field=models.ManyToManyField(blank=True, related_name='excluded_news_articles', to='officers.Officer'),
        ),
    ]
