# Generated by Django 3.1.4 on 2021-10-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0017_auto_20210924_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='excluded_officers',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='extracted_keywords',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='officers',
        ),
    ]
