# Generated by Django 3.1.4 on 2021-10-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0018_remove_nlp_related_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
