# Generated by Django 3.1.4 on 2021-10-14 02:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0022_alter_event_department_uof_fields'),
        ('news_articles', '0019_add_field_is_processed_to_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('extracted_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_sentences', to='news_articles.newsarticle')),
                ('excluded_officers', models.ManyToManyField(blank=True, related_name='excluded_matched_sentences', to='officers.Officer')),
                ('officers', models.ManyToManyField(blank=True, related_name='matched_sentences', to='officers.Officer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
