# Generated by Django 3.1.4 on 2021-10-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0020_create_model_matched_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='link',
            field=models.TextField(unique=True),
        ),
    ]
