# Generated by Django 3.1.4 on 2021-11-02 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0021_alter_field_link_to_textfield_on_newsarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticlesource',
            old_name='custom_matching_name',
            new_name='source_display_name',
        ),
    ]
