# Generated by Django 3.1.13 on 2023-04-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0023_add_is_hidden_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticleClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article_id', models.IntegerField(db_index=True, unique=True)),
                ('text', models.TextField()),
                ('score', models.FloatField(default=0.0)),
                ('relevant', models.CharField(blank=True, max_length=255, null=True)),
                ('truth', models.CharField(blank=True, max_length=255, null=True)),
                ('news_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_article_classifications', to='news_articles.newsarticle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
