# Generated by Django 3.1.4 on 2021-07-21 03:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_recent_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recent_queries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
