# Generated by Django 3.1.4 on 2021-11-04 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officers', '0022_alter_event_department_uof_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_id', models.CharField(blank=True, max_length=255, null=True)),
                ('canonical_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_person', to='officers.officer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
