# Generated by Django 3.1.4 on 2021-11-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_create_model_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='all_complaints_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
