# Generated by Django 3.1.13 on 2023-04-13 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0023_rename_fields_name_and_slug'),
        ('officers', '0038_add_award_to_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brady_uid', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('disposition', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('allegation_desc', models.TextField(blank=True, null=True)),
                ('tracking_id_og', models.CharField(blank=True, max_length=255, null=True)),
                ('charging_agency', models.CharField(blank=True, max_length=255, null=True)),
                ('source_agency', models.CharField(max_length=255)),
                ('agency', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bradies', to='departments.department')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bradies', to='officers.officer')),
            ],
            options={
                'verbose_name_plural': 'bradies',
            },
        ),
    ]
