# Generated by Django 3.1.13 on 2023-05-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brady', '0001_create_brady'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brady',
            name='brady_uid',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
