# Generated by Django 3.1.13 on 2023-08-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0023_rename_fields_name_and_slug'),
        ('officers', '0039_add_brady_to_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOfficerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('history_id', models.CharField(max_length=255)),
                ('agency', models.CharField(max_length=255)),
                ('left_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_officer_histories', to='departments.department')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_officer_histories', to='officers.officer')),
            ],
            options={
                'verbose_name_plural': 'post_officer_histories',
            },
        ),
    ]
