# Generated by Django 3.1.4 on 2021-01-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
        ('documents', '0002_add_fields_to_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='officers',
            field=models.ManyToManyField(blank=True, to='officers.Officer'),
        ),
    ]
