# Generated by Django 3.1.4 on 2021-01-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_change_officers_field_of_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='incident_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pages_count',
            field=models.IntegerField(null=True),
        ),
    ]
