# Generated by Django 3.1.4 on 2021-03-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pages_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
