# Generated by Django 3.1.4 on 2021-03-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
