# Generated by Django 3.1.4 on 2021-05-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0018_add_unique_constraint_to_event_uid'),
        ('departments', '0006_department_officers'),
        ('documents', '0008_allow_null_for_document_incident_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='documents', to='departments.Department'),
        ),
        migrations.AlterField(
            model_name='document',
            name='officers',
            field=models.ManyToManyField(blank=True, related_name='documents', to='officers.Officer'),
        ),
    ]
