# Generated by Django 3.1.4 on 2021-05-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_add_fields_to_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docid',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
