# Generated by Django 3.1.4 on 2021-06-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_add_uniq_and_db_index_for_document_docid'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_db_content_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='hrg_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='matched_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='docid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('docid', 'hrg_no', 'matched_uid')},
        ),
    ]
