# Generated by Django 3.1.4 on 2021-06-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_add_fields_to_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_db_content_hash',
            new_name='pdf_db_content_hash',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='file_db_path',
            new_name='pdf_db_path',
        ),
        migrations.RemoveField(
            model_name='document',
            name='fileid',
        ),
        migrations.AddField(
            model_name='document',
            name='txt_db_content_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='txt_db_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
