# Generated by Django 3.1.13 on 2021-12-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_change_file_fields_and_ocr_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hrg_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
