# Generated by Django 3.1.13 on 2022-01-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_add_hrg_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='agency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('docid', 'hrg_no', 'matched_uid', 'agency')},
        ),
    ]
