# Generated by Django 3.1.13 on 2022-06-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_add_agency_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dt_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='hrg_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pdf_db_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='txt_db_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
